<?php declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>

<div>
    <p class="greeting"><?= $escaper->escapeHtml(__('Hello there')) ?></p>
</div>

<style>
.order-example {
    @apply bg-white py-6 px-4;
    color: theme('colors.gray.800');
    colrs: red;

    @screen md {
        @apply my-2;
    }
}
</style>
